<?php

namespace Database\Seeders;

use App\Models\Artist;
use App\Models\Category;
use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class InitData extends Seeder
{
    public function run()
    {
        $this->insertCountries();
        $this->insertCategories();
//        $this->insertArtists();
//        $this->insertClients();
    }

    private function insertCountries()
    {
        $countryNames = [
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "The Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "Congo, Democratic Republic of the",
            "Congo, Republic of the",
            "Costa Rica",
            "Côte d’Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czech Republic",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "East Timor (Timor-Leste)",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "The Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Korea, North",
            "Korea, South",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia, Federated States of",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar (Burma)",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Sudan, South",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ];

        foreach ($countryNames as $countryName) {
            Country::create(['country' => $countryName]);
        }
    }

    private function insertCategories()
    {
        $categoryNames = [
            "Vector Painting",
            "3D Modeling",
            "Digital Painting",
            "2D Digital Painting",
            "3D Digital Painting And Sculpting",
            "Pixel Art",
            "Raster Painting",
            "2D Animation",
            "3D Animation",
            "Logos",
            "Photo Painting",
            "Digital Collage",
            "CGI Art",
            "Fractal Art"
        ];

        foreach ($categoryNames as $categoryName) {
            Category::create(['category' => $categoryName]);
        }
    }

    private function insertArtists()
    {
        $artists = [
            [
                'name' => 'Emily Chang',
                'username' => 'emily.chang',
                'password' => 'emily123',
                'age' => 35,
                'jobTitle' => 'Graphic Designer',
                'hourlyRate' => 12.5,
                'summary' => "Hi there! I'm Emily Chang...",
                'countryId' => 125,
                'portfolio' => '/resources/uploads/emily.chang-portfolio.pdf',
                'profilePicture' => '/resources/uploads/emily.chang-profile-picture.png',
                'role' => 'ARTIST',
            ],
            [
                'name' => 'Jamal Patel',
                'username' => 'jamal.patel',
                'password' => 'jamal123',
                'age' => 30,
                'jobTitle' => 'Illustrator',
                'hourlyRate' => 10.0,
                'summary' => "Hey, I'm Jamal Patel...",
                'countryId' => 163,
                'portfolio' => '/resources/uploads/jamal.patel-portfolio.pdf',
                'profilePicture' => '/resources/uploads/jamal.patel-profile-picture.png',
                'role' => 'ARTIST',
            ],
        ];

        foreach ($artists as $artistData) {
            Artist::create([
                'name' => $artistData['name'],
                'username' => $artistData['username'],
                'password' => Hash::make($artistData['password']),
                'age' => $artistData['age'],
                'jobTitle' => $artistData['jobTitle'],
                'hourlyRate' => $artistData['hourlyRate'],
                'summary' => $artistData['summary'],
                'countryId' => $artistData['countryId'],
                'portfolio' => $artistData['portfolio'],
                'profilePicture' => $artistData['profilePicture'],
                'role' => $artistData['role'],
            ]);
        }


    }
}
